#!/usr/bin/env python3
"""Generates docs/SUPPORTED_TOYS.md from app/src/main/assets/devices.json.

A protocol counts as supported when it is registered in
app/src/main/java/com/edge2/remote/ble/proto/Registry.kt.

Usage: tools/gen_supported.py
"""
import json
import re
from collections import defaultdict

DB = "app/src/main/assets/devices.json"
REGISTRY = "app/src/main/java/com/edge2/remote/ble/proto/Registry.kt"
OUT = "docs/SUPPORTED_TOYS.md"

# Protocol ids registered through companion objects / objects (not visible as literals in Registry.kt).
SPEC_SOURCES = "app/src/main/java/com/edge2/remote/ble/proto"

ICONS = [
    ("vibrate", "📳", "vibration"),
    ("rotate", "🔄", "rotation"),
    ("oscillate", "↕️", "thrust / oscillation"),
    ("constrict", "💨", "suction / constriction"),
    ("temperature", "🔥", "heating"),
    ("led", "💡", "light"),
    ("spray", "💧", "lube pump"),
    ("hw_position_with_duration", "🎚️", "stroker"),
    ("position", "🎚️", "stroker"),
]


def supported_ids():
    import glob
    text = "".join(open(f, encoding="utf-8").read() for f in glob.glob(SPEC_SOURCES + "/*.kt"))
    ids = set(re.findall(r'spec(?:Init)?\("([a-z0-9_-]+)"', text))
    ids |= set(re.findall(r'override val id = "([a-z0-9_-]+)"', text))
    ids |= set(re.findall(r'spec\("([a-z0-9_-]+)",', text))
    ids |= set(re.findall(r'(?:vibCrafter|vibio) = spec\("([a-z0-9_-]+)"', text))
    return ids


def icons(features):
    types = set()
    for f in features or []:
        types |= set(f.get("o", {}).keys())
    seen, out = set(), []
    for key, icon, _ in ICONS:
        if key in types and icon not in seen:
            seen.add(icon)
            out.append(icon)
    return " ".join(out)


def brand(p):
    return (p.get("defaults", {}).get("name") or p["id"]).replace(" Device", "").strip()


def main():
    db = json.load(open(DB, encoding="utf-8"))
    ok = supported_ids()
    by_brand = defaultdict(list)
    unsupported = []
    total = 0
    for p in db["protocols"]:
        if p["id"] not in ok:
            unsupported.append(p)
            continue
        defaults = p.get("defaults", {})
        names = sorted({(c["name"], icons(c.get("f", defaults.get("f")))) for c in p["configs"]})
        if not names:
            names = [(defaults.get("name", p["id"]), icons(defaults.get("f")))]
        b = brand(p)
        by_brand[b].extend((n, i, p["id"]) for n, i in names)
    lines = [
        "# Supported toys",
        "",
        "_Generated by `tools/gen_supported.py` from the device database — do not edit by hand._",
        "",
        "Legend: " + " · ".join(f"{icon} {label}" for key, icon, label in ICONS if key != "position"),
        "",
        "**Lovense** is tested on hardware; every other brand is **experimental**: its",
        "protocol comes from the [Buttplug](https://github.com/buttplugio/buttplug) community",
        "database and hasn't been verified on a real toy by this project.",
        "",
    ]
    brands = sorted(by_brand, key=lambda b: (b != "Lovense", b.lower()))
    for b in brands:
        models = sorted(set(by_brand[b]))
        total += len(models)
    lines.insert(4, f"**{total} models** across **{len(brands)} brands / families**.\n")
    for b in brands:
        models = sorted(set(by_brand[b]))
        lines.append(f"## {b}{'' if b == 'Lovense' else ' (experimental)'}")
        lines.append("")
        for name, ic, pid in models:
            lines.append(f"- {name} {ic}".rstrip())
        lines.append("")
    if unsupported:
        lines.append("## Recognised but not supported yet")
        lines.append("")
        for p in sorted(unsupported, key=lambda p: p["id"]):
            lines.append(f"- {brand(p)} (`{p['id']}`)")
        lines.append("")
    open(OUT, "w", encoding="utf-8").write("\n".join(lines))
    print(f"{total} models, {len(brands)} brands → {OUT}")


if __name__ == "__main__":
    main()
